# Generated by Django 6.0.7 on 2026-07-16 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('VOLUNTEER', 'Volunteer')], default='FULL_TIME', max_length=15)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('WAEC', 'WAEC/NECO'), ('OND', 'OND'), ('HND', 'HND'), ('BSC', 'B.Sc / B.Ed'), ('MSC', 'M.Sc / M.Ed'), ('PHD', 'Ph.D'), ('OTHER', 'Other')], max_length=10)),
                ('institution', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year_obtained', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='staff_certificates/')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('class_assigned', models.ForeignKey(blank=True, help_text='The class this teacher is a form/class teacher for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='academics.classarm')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='staff.staff')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
