# Generated by Django 6.0.7 on 2026-07-16 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Session Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Session')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Class Level')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first (e.g. JSS1=1, SS3=6).', verbose_name='Order')),
                ('section', models.CharField(choices=[('JUNIOR', 'Junior Secondary'), ('SENIOR', 'Senior Secondary')], max_length=10, verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(help_text='Short unique code, e.g. MTH, ENG, BIO.', max_length=10, unique=True, verbose_name='Subject Code')),
                ('is_compulsory', models.BooleanField(default=True, verbose_name='Compulsory')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Assignment',
                'verbose_name_plural': 'Subject Assignments',
                'ordering': ['session', 'term', 'class_arm', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('FIRST', 'First Term'), ('SECOND', 'Second Term'), ('THIRD', 'Third Term')], max_length=10, verbose_name='Term')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Term')),
                ('next_term_begins', models.DateField(blank=True, null=True, verbose_name='Next Term Begins')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession', verbose_name='Academic Session')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['session', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Arm Name')),
                ('capacity', models.PositiveSmallIntegerField(default=40, verbose_name='Capacity')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='academics.classlevel', verbose_name='Class Level')),
            ],
            options={
                'verbose_name': 'Class Arm',
                'verbose_name_plural': 'Class Arms',
                'ordering': ['class_level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academics.classarm', verbose_name='Class Arm')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academics.academicsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Class Teacher Assignment',
                'verbose_name_plural': 'Class Teacher Assignments',
                'ordering': ['session', 'class_arm'],
            },
        ),
    ]
