# Generated by Django 6.0.7 on 2026-07-16 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Class Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Department Head'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_levels',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classlevel', verbose_name='Class Levels'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_arm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.classarm', verbose_name='Class Arm'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.academicsession', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['TEACHER', 'CLASS_TEACHER']}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.academicterm', verbose_name='Term'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('session', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classarm',
            unique_together={('class_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classteacherassignment',
            unique_together={('class_arm', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('teacher', 'subject', 'class_arm', 'session', 'term')},
        ),
    ]
