from django.db import models
from django.conf import settings
from core.models import TimeStampedModel


class Announcement(TimeStampedModel):
    """School-wide announcements with role targeting."""
    PRIORITY_CHOICES = [
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium'),
        ('HIGH', 'High'),
        ('URGENT', 'Urgent'),
    ]
    title = models.CharField(max_length=255)
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, null=True,
        related_name='announcements'
    )
    target_roles = models.JSONField(
        default=list,
        help_text='List of role codes that can see this announcement, e.g. ["STUDENT", "PARENT"]. Empty = all.'
    )
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='MEDIUM')
    is_published = models.BooleanField(default=False)
    publish_date = models.DateTimeField(null=True, blank=True)
    expiry_date = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Announcement'
        verbose_name_plural = 'Announcements'

    def __str__(self):
        return self.title

    def is_visible_to(self, user):
        if not self.is_published:
            return False
        if not self.target_roles:
            return True
        return user.role in self.target_roles


class Notification(TimeStampedModel):
    """Per-user notifications generated by system events."""
    TYPE_CHOICES = [
        ('INFO', 'Information'),
        ('SUCCESS', 'Success'),
        ('WARNING', 'Warning'),
        ('DANGER', 'Danger'),
        ('PAYMENT', 'Payment'),
        ('RESULT', 'Result'),
        ('ADMISSION', 'Admission'),
    ]
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='notifications'
    )
    title = models.CharField(max_length=150, blank=True)
    message = models.TextField()
    notification_type = models.CharField(max_length=15, choices=TYPE_CHOICES, default='INFO')
    link = models.CharField(max_length=255, blank=True, help_text='Optional URL to redirect to on click')
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'

    def __str__(self):
        return f"[{self.notification_type}] {self.user.username}: {self.message[:50]}"

    @classmethod
    def send(cls, user, message, title='', notification_type='INFO', link=''):
        """Convenience factory method."""
        return cls.objects.create(
            user=user,
            message=message,
            title=title,
            notification_type=notification_type,
            link=link,
        )


class Message(TimeStampedModel):
    """Internal messaging between portal users."""
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sent_messages'
    )
    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='received_messages'
    )
    subject = models.CharField(max_length=255)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='replies'
    )
    is_archived_by_sender = models.BooleanField(default=False)
    is_archived_by_recipient = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return f"From {self.sender} to {self.recipient}: {self.subject[:50]}"
